### ISSUE TITLE
Improve Aeracoop App: controls, data visualization, platform agnosticity // Mejorar aplicación de Aeracoop: controles, visualización de datos, agnosticidad de plataforma

### ISSUE THREAD

**Issue by NicolasNarvaez** [vuelaendron/vuela#13]
Currently we use the [Fewlaps app](https://github.com/Fewlaps/flone-android) backed by Aeracoop to controll the flone, but it only works on android, the interface is not comfortable enough and has troubles in the yaw axis. 

We contacted Aeracoop about this and the relationship between the older [repository](https://github.com/aeracoop/flone) and the new one (above) and they say that the older repository is deprecated and pointed out that for an update or a full app rewrite is necesary to keep a service proccess alive (to avoid calls taking down the app) and that some drivers arent waranteed to work on common multiplatform systems, like bluetooth module on a react app, for example.

I propose to rewrite the app in a cordoba app with a meteor or vue/react frontend and port the drivers and service worker into a cordova plugin to make it platform agnostic and add new functions like computer/internet controll (maybe using socketio) that are current issues in the android app.

***
***

Actualmente usamos la [aplicación de Fewlaps](https://github.com/Fewlaps/flone-android) respaldada por Aeracoop para controlar el flone, pero solo funciona en android, la interfaz es incómoda y tiene problemas con el eje Yaw.

Contactamos a Aeracoop hacerca de esto y la relación entre el [repositorio viejo](https://github.com/aeracoop/flone) y el nuevo (arriba) y respondieron que el repositorio viejo está deprecado, y indicaron que para una actualización o una reescritura completa de la app es necesario mantener un servicio paralelo vivo (para evitar que las llamadas echen abajo el flone) y que algunos drivers no estan garantizados de funcionar en los sistemas multiplataforma comunes como por ejemplo el modulo bluetooth en una aplicación react.

Propongo reescribir la app como una app cordoba con un frontend meteor o vue/react y portar los drivers y el service worker en un plugin cordoba para hacerlo agnóstico de plataforma y agregar nuevas funciones como control por computador/internet (quizá usando socket.io) que son problemas actuales en la aplicación de android.

**Comment by gpereyrairujo** [comment]
Suena bien! Qué opinan @lotelx @rocboronat?

Sounds good! What do you think @lotelx @rocboronat?

**Comment by lotelx** [comment]
I think that this kind of apps (control a drone) is a critical process, will be better to use Android Native.
Every milisecond counts, even with the native android app there is a small delay, we keep it reasonable to fly, but with a non-native this latency will increase.

**Comment by gpereyrairujo** [comment]
Respecto de la interfaz, yo personalmente no la encuentro incómoda (aunque obviamente no es lo mismo que un radiocontrol profesional). Qué propones cambiarle @NicolasNarvaez ?

Regarding the interface, personally I don't find it uncomfortable (although it is obviously not the same as a professional radio transmitter). What changes do you propose, @NicolasNarvaez ?

**Comment by PabloReszczynski** [comment]
I agree that making the control process should be made native and as low level as possible to minimize latency problems. Still it can be possible to make the interface with a higher level framework like cordoba and react native.

**Comment by rocboronat** [comment]
Hello team!

Feel free to rewrite the app in whatever technology you prefer, but my advice is to think twice about it. I was lucky finding an Android library that wrapped most of the bluetooth calls from the phone to the drone's board, but you could not be as lucky as I was finding something like that in such technologies as Cordova, React... In addition, keep an eye on the performance, because it's kinda hard to keep lag as low as possible. I crashed some drones while developing the app... 😅

By the way, I quitted the project because I'm traveling around the world for some long time, but feel free to send PR's to improve the layout if you have the time to do it. Or just fork the project and invest some time in it. You're more than welcome to it, and I will proudly forward all the Fewlaps' repository visits to your fork, declaring ours as deprecated.

Thanks for making things fly!
